formatVersion: 1
Cloud_Machine: null
inputs:
  hostname1:
    type: string
  user:
    type: string
    title: Username for SSH
    description: The username you would like to have for the installation.
    default: demouser
  password:
    type: string
    pattern: '[a-z0-9A-Z@#$]+'
    encrypted: true
    title: Admin Account Password
    description: The password you would like to use for the System resources
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    metadata:
      layoutPosition:
        - 0
        - 0
    properties:
      image: VMW-CentOS
      flavor: VMW-Small
      cloudConfig:
        #cloud-config
        hostname: '${input.hostname1}'
        users:
          - name: '${input.user}'
            sudo:
              - 'ALL=(ALL) NOPASSWD:ALL'
            groups: sudo
            shell: /bin/bash
        runcmd:
          - 'PASS=${input.password}'
          - 'USER=${input.user}'
          - 'echo $USER:$PASS | /usr/sbin/chpasswd'
          - sed -i "s/PasswordAuthentication no /PasswordAuthentication yes/g" /etc/ssh/sshd_config
          - service ssh reload
      # customizationSpec: Lin-Cust
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
          assignment: static
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      networkType: existing
      name: VMW-Production
      networkCidr: 172.20.11.0/24
