apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: ${input.Namespace}
spec:
  selector:
    matchLabels:
      run: apache
  replicas: ${input.NumberReplicas}
  template:
    metadata:
      namespace: ${input.Namespace}
      labels:
        run: apache
    spec:
      containers:
      - name: apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
